config/routes.rb
Rails.application.routes.draw do
  get 'badges/index'
  get 'badges/new'
  get 'badges/show'
  get 'badges/create'
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  get 'gists/index'
 
  scope "(:locale)", locale: /en|ru|/ do
    root "tests#index"

    get :about, action: :about, controller: 'application'
    get :my_badges, action: :my_badges, controller: 'badges'
    
    resource :contact, only: [:new, :create], controller: 'contact', path_names: { new: '/', create: '/' }

    devise_for :users, path: :students, path_names: { sign_in: :login, sign_out: :logout }
   
    resources :tests, only: :index do
      member do
        post :start
      end
    end

    namespace :admin do
      resources :gists, only: :index
      resources :reward_rules
      resources :badges
      resources :tests do
        resources :questions, shallow: true do
          resources :answers, shallow: true
        end
      end
    end

    # GET /results/1/finish
    resources :results, only: %i[show update] do
      member do
        get   :finish
        post  :gist, as: 'new_gist'
      end
    end
  end

end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users_badges, dependent: :destroy
  has_many :users, through: :users_badges
  belongs_to :reward_rule
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[edit update destroy]
  before_action :set_images, only: %i[new edit]

  def index
    @badges  = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def edit
  end

  def show
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path
    else
      set_images
      render :new
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path, notice: "Бейдж был удален"
  end


  private
  
  def set_images
    @images = Dir['app/assets/images/badges/*'].map { |img| img.gsub!('app/assets/images/', '') }
  end
  
  def set_badge
    @badge = Badge.find(params[:id])
  end
  
  def badge_params
    params.require(:badge).permit(:title, :image, :reward_rule_id)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def my_badges
    # @badges = Badge.connection.select_all('Select COUNT(badges.id), title, image from badges group by badges.title, badges.image')
    @badges = current_user.badges.select('count(badges.id), badges.id, title, image').group(:id)
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, object] do |form| %>

  <div class="form-floating my-3 col-md-5">
    <%= form.text_field :title, class: "form-control" %>
    <%= form.label t('.title'), for: :title %>
  </div>

  <div class="slider col-md-2 my-4">
    <%= form.text_field :image, class: "form-control", id: 'imagename', type: "hidden", value: object.image %>
    <div class="slider__container">
      <div class="slider__wrapper">
        <div class="slider__items">
          <% @images.each do |value| %>
            <div class="slider__item" data-imagename="<%= value %>">
              <%= image_tag value, class: "bi d-block mx-auto mb-1", size: 24 %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <a href="#" class="slider__control" data-slide="prev"></a>
    <a href="#" class="slider__control" data-slide="next"></a>
  </div>

  <div class="row">
    <div class="form-floating col-md-5">
      <%= collection_select(:badge, :reward_rule_id, RewardRule.all, :id, :title, { prompt: true }, { class: "form-select", id: "reward_rule_select" }) %>
      <%= form.label t('.rule'), class: "ms-2", for: "reward_rule_select" %>
    </div>
    <div class="col-md-2">   
        <%= link_to t('.new_rule'), new_admin_reward_rule_path, class: "btn btn-link mt-2"  %>
    </div>
  </div>

  <div>
    <%= form.submit object.new_record? ? t('create') : t('update'), class: "btn btn-primary col-lg-2 mt-3", id: "postbadgebutton" %>
  </div>

  <%= link_to t('nav_back'), admin_badges_path, class: "btn btn-link mt-2"  %>
  
<% end %>

app/views/admin/badges/edit.html.erb
<h1><%= t('.edit_rule') %></h1>

<%= render 'shared/errors', object: @badge %>
<%= render 'form', object: @badge %>

app/views/admin/badges/index.html.erb
<h1>Badges</h1>
  
  <div class="col-md-1">
    <%= link_to t('.add_new'), new_admin_badge_path, class: "btn btn-link my-2 border" %>
  </div>
  
  <% @badges.each do |badge| %>
    <div class="row my-2">
      <%= image_tag(badge.image, size: 25, class: "col-sm-1 p-0 align-self-center", style: 'width:50px') if badge.image %>
      <span class="col-md-2 align-middle p-0"><%= badge.title %></span>
 
      <div class="col-md-2 mx-1">
        <%= link_to image_tag('edit.svg', size: 12), edit_admin_badge_path(badge) %> |
        <%= link_to image_tag('delete.svg', size: 12), admin_badge_path(badge), method: :delete %>
      </div>
    </div>
  <% end %>

<%= link_to t('nav_back'), root_path %>

app/views/admin/badges/new.html.erb
<h1><%= t('.new_badge') %></h1>

<%= render 'shared/errors', object: @badge %>
<%= render 'form', object: @badge %>