config/routes.rb
Rails.application.routes.draw do
  get 'badges/index'
  get 'badges/new'
  get 'badges/show'
  get 'badges/create'
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  get 'gists/index'
 
  scope "(:locale)", locale: /en|ru|/ do
    root "tests#index"

    get :about, action: :about, controller: 'application'
    get :my_badges, action: :my_badges, controller: 'badges'
    
    resource :contact, only: [:new, :create], controller: 'contact', path_names: { new: '/', create: '/' }

    devise_for :users, path: :students, path_names: { sign_in: :login, sign_out: :logout }
   
    resources :tests, only: :index do
      member do
        post :start
      end
    end

    namespace :admin do
      resources :gists, only: :index
      resources :reward_rules
      resources :badges
      resources :tests do
        resources :questions, shallow: true do
          resources :answers, shallow: true
        end
      end
    end

    # GET /results/1/finish
    resources :results, only: %i[show update] do
      member do
        get   :finish
        post  :gist, as: 'new_gist'
      end
    end
  end

end

app/models/admin.rb
class Admin < User
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_answers_count

  scope :right_aswers, -> { where(correct: true) }

  private

  def validate_answers_count
    errors.add(:Question, "already has 4 answers") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users_badges, dependent: :destroy
  has_many :users, through: :users_badges
  belongs_to :reward_rule
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  validates :title, presence: true

  scope :all_by_title, -> { order(:title) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :author, class_name: "User"

  validates :question, presence: true, uniqueness: { scope: :author }
  validates :gist_id, presence: true, uniqueness: true

  def initialize(args)
    super
    create_gist_on_gitgub
  end

  private 

  def create_gist_on_gitgub
    new_gist = GistQuestionService.new
    self.gist_id = new_gist.create_gist(self).id
    unless new_gist.client.last_response.status == 201
      errors.add(:gist_id, "Ошибка при запросе на GitHub")
    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: "Question", optional: true

  before_create :before_create_set_qst
  before_update :before_update_next_qst
  before_update :before_update_check_final_results

  PASSING_LIMIT = 85

  def answered_questions
    test.questions.where('id < ?', current_question.id).count
  end

  def accept!(answer_id)
    self.correct_questions += 1 if current_question.answers.find(answer_id).correct
    save!
  end

  def completed?
    finished_at.present? 
  end

  def success?
    score >= PASSING_LIMIT
  end

  private

  def before_create_set_qst
    self.current_question = test.questions.first if test.present? && current_question.nil?
  end

  def before_update_next_qst
    self.current_question = test.questions.where('id > ?', current_question.id).order(:id).first if test.present? && !completed?
  end

  def before_update_check_final_results    
    
    #if current_question is nil, means those was the last question and this test has been completed in time
    self.finished_at = Time.now unless current_question
    
    if completed? 
      self.score = (self.correct_questions.to_f / test.questions.count * 100)
      self.passed = success?
    end
  end
end

app/models/reward_rule.rb
class RewardRule < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :results, dependent: :destroy
  has_many :users, through: :results
  has_many :questions, dependent: :destroy
  belongs_to :category
  belongs_to :author, class_name: "User"

  validates :title, presence: true, uniqueness: { scope: :level }

  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validate :validate_activation, on: :update, if: Proc.new { is_active }

  scope :easy, -> { where(level: (0..1)) }
  scope :normal, -> { where(level: (2..5)) }
  scope :hard, -> { where(level: (5..)) }

  scope :by_category, ->(str) { joins(:category).where('categories.title like :str', str: "%#{str}%") }

  def level_represent
    return :easy if level <= 1
    return :normal if (2..5).include?(level)
    return :hard
  end

  def self.find_by_title_category(str)
    by_category(str).order("tests.title DESC").pluck("tests.title")
  end

  private

  def validate_activation 
    errors.add(:Test, ": to activate it has to include at least one question!") if questions.count == 0
  end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, 
          :registerable,
          :recoverable, 
          :rememberable, 
          :validatable,
          :confirmable

  has_many :tests_by_me, class_name: "Test", foreign_key: "author_id"
 
  has_many :results
  has_many :tests, through: :results
 
  has_many :users_badges, dependent: :destroy
  has_many :badges, through: :users_badges

  validates :email, presence: true, uniqueness: true, format: URI::MailTo::EMAIL_REGEXP
  validates :first_name, presence: true

  def admin?
    self.is_a?(Admin)
  end

  def my_tests(level = nil)
    tests.where('tests.level = :level or :level is null', level:)
  end

  def test_passing(test)
    results.where(test: test, finished_at: nil).where.not(current_question: nil).first
  end
end

app/models/users_badge.rb
class UsersBadge < ApplicationRecord
  belongs_to :badge
  belongs_to :user
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def this_year
    Time.now.year
  end

  def github_url(author, repo)
    link_to "https://github.com/#{author.strip}/#{repo.strip}"
  end

  def flash_msg
    flash.map do |key, value|
      if value.is_a?(Array)
          value.map do |subvalue|
              content_tag :div, subvalue.try(:html_safe), class: "alert alert-#{devise_status_to_bootstrap(key)} m-3", role: "alert"
          end
      else
        content_tag :div, value.try(:html_safe), class: "alert alert-#{devise_status_to_bootstrap(key)} m-3", role: "alert"
      end
    end.join().html_safe if flash.any?
  end

  def devise_status_to_bootstrap(key)
    case key
    when "alert"
      "danger"
    when "notice"
      "success"
    else
      key
    end
  end

end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  def question_header(question)
    question.new_record? ? "Create New #{question.test.title} Question" : "Edit #{question.test.title} Question"
  end
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div style="color: red">
    <h2><%= t("errors.messages.not_saved", resource: object.class.to_s, count: object.errors.count) %>  </h2>

    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<hr>
<footer class="m-3">
  <p><strong>TestGuru, <%= github_url("skvortsovvg", "TestGuru") %></strong></p>
  <p>Учебный проект в онлайн-школе <a href="http:\\thinknetica.com" target="_blank" rel="noopener">Thinknetica</a></p>
  <p><%= this_year %>, Владимир Скворцов (TG, skype: @skvortsovvg)</p>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-sm border" style="background-color: #e3f2fd;">
  <div class="container ms-3 justify-content-start">
    <%= image_tag "test.png", size: "32", style: "margin-right: 5px" %> 
    <a class="navbar-brand pe-4 border-end border-primary border-3 align-self-center" style="height: 40px;" href=<%= root_path %>>TestGuru</a>
    
    <div class="container g-0 justify-content-start">
      <ul class="navbar-nav">      
        <% if current_user&.admin? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= image_tag "gear.svg", class: "bi d-block mx-auto mb-1", size: 24 %>
            <%= t(".admin") %>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href=<%= admin_tests_path %>><%= t(".tests") %></a></li>
            <li><a class="dropdown-item" href=<%= admin_badges_path %>><%= t(".badges") %></a></li>
            <li><a class="dropdown-item" href=<%= admin_reward_rules_path %>><%= t(".rules") %></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href=<%= admin_gists_path %>>Gists</a></li>
          </ul>
        </li>
        <% end %>
        <% if current_user %>
        <li class="nav-item">
          <a class="nav-link text-primary" href=<%= my_badges_path %>>
            <%= image_tag "list.svg", class: "bi d-block mx-auto mb-1", size: 24 %>
            <%= t(".badges") %>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-primary" href=<%= new_contact_path %>>
            <%= image_tag "at-solid.svg", class: "bi d-block mx-auto mb-1", size: 24%>
            <%= t(".contact") %>
          </a>
        </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link text-primary" href=<%= about_path %>>
            <%= image_tag "info.svg", class: "bi d-block mx-auto mb-1", size: 24%>
            <%= t(".about") %>
          </a>
        </li>
      </ul>
    </div>
  </div>
  
  <div class="container me-3 justify-content-end">
    <div class="dropdown pe-3">
      <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
        <img src=<%= t('.f_pic') %> width="32" height="32" class="rounded-circle">
        <%= t(I18n.locale) %>
      </a>
      <ul class="dropdown-menu">
        <% I18n.available_locales.each do |locale| %>
          <li>
            <a class="dropdown-item" href=<%= url_for(locale: locale) %>><%= t(locale) %> </a>
          </li>
        <% end %>
      </ul>
    </div>

    <ul class="nav-sm navbar-nav ps-2 border-start border-primary border-3" style="height: 40px;">
      <% if current_user %>
        <li class="nav-item pe-2 border-end border-primary border-3 align-self-center"><%= t('welcome') %>, <b><%= current_user.first_name %></b> Guru</li>
        <li class="nav-item ps-2 align-self-center"><%= button_to t('.logout'), destroy_user_session_path, method: :delete, class: "btn btn-primary", style: "--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .85rem;"%></li>      
      <% else %>
        <li class="nav-item align-self-center ps-1"><%= button_to t('.login'), new_user_session_path, method: :get, class: "btn btn-primary me-2" %></li>
        <li class="nav-item align-self-center"><%= button_to t('.register'),  new_user_registration_path, method: :get, class: "btn btn-primary" %></li>
      <% end %>
      </ul>        
    </div>
  </div>
</nav>