config/routes.rb
Rails.application.routes.draw do
  get 'badges/index'
  get 'badges/new'
  get 'badges/show'
  get 'badges/create'
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  get 'gists/index'
 
  scope "(:locale)", locale: /en|ru|/ do
    root "tests#index"

    get :about, action: :about, controller: 'application'
    get :my_badges, action: :my_badges, controller: 'badges'
    
    resource :contact, only: [:new, :create], controller: 'contact', path_names: { new: '/', create: '/' }

    devise_for :users, path: :students, path_names: { sign_in: :login, sign_out: :logout }
   
    resources :tests, only: :index do
      member do
        post :start
      end
    end

    namespace :admin do
      resources :gists, only: :index
      resources :reward_rules
      resources :badges
      resources :tests do
        resources :questions, shallow: true do
          resources :answers, shallow: true
        end
      end
    end

    # GET /results/1/finish
    resources :results, only: %i[show update] do
      member do
        get   :finish
        post  :gist, as: 'new_gist'
      end
    end
  end

end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: "Question", optional: true

  before_create :before_create_set_qst
  before_update :before_update_next_qst
  before_update :before_update_check_final_results

  PASSING_LIMIT = 85

  def answered_questions
    test.questions.where('id < ?', current_question.id).count
  end

  def accept!(answer_id)
    self.correct_questions += 1 if current_question.answers.find(answer_id).correct
    save!
  end

  def completed?
    finished_at.present? 
  end

  def success?
    score >= PASSING_LIMIT
  end

  private

  def before_create_set_qst
    self.current_question = test.questions.first if test.present? && current_question.nil?
  end

  def before_update_next_qst
    self.current_question = test.questions.where('id > ?', current_question.id).order(:id).first if test.present? && !completed?
  end

  def before_update_check_final_results    
    
    #if current_question is nil, means those was the last question and this test has been completed in time
    self.finished_at = Time.now unless current_question
    
    if completed? 
      self.score = (self.correct_questions.to_f / test.questions.count * 100)
      self.passed = success?
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_result
  before_action :set_gist, only: [:show, :gist]

  def show; end

  def finish
    @result.update(finished_at: Time.now) if params[:time_up]
  end

  def update
    if params[:answer_id].blank?
      redirect_to(@result, alert: t('.alert_make_choise')) 
    else
      @result.accept!(params[:answer_id])
      if @result.completed?
        BadgesRewardService.check_rewards(@result, current_user).each do |badge|
          flash[:notice] ||= [] 
          flash[:notice] << "Получен новый бейдж: <strong>#{badge}</strong>"
        end 
        redirect_to finish_result_path(@result)
      else
        redirect_to result_path(@result)
      end
    end
  end

  def gist
    return if @gist

    gist = Gist.new(
      question: @result.current_question, 
      author: @result.user,
      content: "#{@result.current_question.body}\n" + @result.current_question.answers.pluck(:body).join("\n"),
      description: t('.gist_discription'),
      public: true)

    if gist.errors.any? || !gist.save
      flash[:alert] = gist.errors.full_messages.join("\n") 
    else 
      flash[:success] = "#{t('.new_gist')}:  #{ view_context.link_to(gist.gist_id, "https://gist.github.com/#{gist.gist_id}", target: '_blank') }" 
    end
    redirect_to @result

  end

  private

  def set_result
    @result = Result.find(params[:id])
  end
  
  def set_gist
    @gist = Gist.find_by(question: @result.current_question, author: current_user)
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/finish.html.erb
<h1>Тест завершен!</h1>

<% if @result.passed %>
  <h2 style="color: green"><span style="color: black">Ваш результат:</span> <%= @result.score %>%</h2>
  <h2 style="color: green">ТЕСТ УСПЕШНО ПРОЙДЕН!</h2>
<% else %>
  <h2 style="color: red"><span style="color: black">Ваш результат:</span> <%= @result.score %>%</h2>
  <h2 style="color: red">ТЕСТ НЕ ПРОЙДЕН!</h2>
<% end %>

<%= link_to "К тестам", tests_path %>

app/views/results/show.html.erb
<h1 style="margin-bottom: 10px;"><%= t(".title") %> "<%= @result.test.title %>"</h1>

<div class="progress mb-2">
  <% prev_value = @result.answered_questions > 0 ? (@result.answered_questions-1).to_f/@result.test.questions.count*100 : 0 %>
  <div class="progress-bar" role="progressbar" style="width: <%= "#{prev_value}%" %>" aria-valuemin="0" aria-valuemax="100"><%= "#{'%.2f' % prev_value }%" %></div>
</div>

<div class="modal fade" id="time_is_up" data-bs-backdrop="static" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="text-center modal-title">Тестирование завершено</h5>
      </div>
      <div class=" text-center modal-body">
        <%= @current_user.first_name %>, отведенное время для данного тестирования истекло! К сожалению, вы не успели пройти весь тест. Попробуйте в другой раз. 
      </div>
      <div class="modal-footer">
        <%= button_to "Результат", finish_result_path(@result), class: "btn btn-primary", method: :get, data: { 'bs-dismiss': "modal params"}, params: { time_up: 3.month.ago } %>
      </div>
    </div>
  </div>
</div>

<%= form_with url: result_path(@result), method: :put do |form| %>
<%= render "shared/errors", object: @result %>

  <div class="card" data-current-qst-number="<%= @result.answered_questions %>" data-qst-count="<%= @result.test.questions.count %>">
    <div class="card-header py-0">

      <div class="d-flex m-1">
        <div class="p-2 w-100">
          <strong><%= "#{ Question.model_name.human} №#{@result.answered_questions + 1}. " %></strong><%= @result.current_question.body %> 
        </div>
      <div class="p-2 flex-shrink-2 align-self-center border-start border-2 border-opacity-75" style="visibility: hidden" id="clock">
          <div class="d-flex px-3">
            <%= image_tag "clock.svg", size: 24 %>  
            <div class="ps-3" id="timer" data-time_out="<%= (@result.created_at + @result.test.timespan.minutes).to_s if @result.test.timespan > 0 %>">00:00</div>
          </div>
      </div>
    </div>
    </div>
    <div class="card-body">
      <%= form.collection_radio_buttons :answer_id, @result.current_question.answers, :id, :body, include_hidden: false do |b| %>
        <p>
          <%= b.radio_button class: "form-check-input align-middle" %>
          <%= b.label class: "form-check-label ms-2 align-middle" %>
        </p>
      <% end %>
      <%= link_to t('.to_tests'), tests_path, class: "btn btn-primary" %>
      <%= form.submit t('.next'), class: "btn btn-success" %>    
    </div>
    <div class="card-footer text-muted">
      <%= "#{@result.answered_questions + 1} из #{@result.test.questions.count}" %> | 
      <% if @gist %> 
        <%= link_to "Gist: #{@gist.gist_id}", "https://gist.github.com/" + @gist.gist_id %>
      <% else %>
        <%= link_to t('.create_new_gist'), new_gist_result_path(@result), method: :post %>
      <% end %>
    </div>
  </div>
  
<% end %>