config/routes.rb
Rails.application.routes.draw do
  get 'badges/index'
  get 'badges/new'
  get 'badges/show'
  get 'badges/create'
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  get 'gists/index'
 
  scope "(:locale)", locale: /en|ru|/ do
    root "tests#index"

    get :about, action: :about, controller: 'application'
    get :my_badges, action: :my_badges, controller: 'badges'
    
    resource :contact, only: [:new, :create], controller: 'contact', path_names: { new: '/', create: '/' }

    devise_for :users, path: :students, path_names: { sign_in: :login, sign_out: :logout }
   
    resources :tests, only: :index do
      member do
        post :start
      end
    end

    namespace :admin do
      resources :gists, only: :index
      resources :reward_rules
      resources :badges
      resources :tests do
        resources :questions, shallow: true do
          resources :answers, shallow: true
        end
      end
    end

    # GET /results/1/finish
    resources :results, only: %i[show update] do
      member do
        get   :finish
        post  :gist, as: 'new_gist'
      end
    end
  end

end

app/models/reward_rule.rb
class RewardRule < ApplicationRecord
end

app/controllers/admin/reward_rules_controller.rb
class Admin::RewardRulesController < Admin::BaseController
  before_action :set_rule, only: %i[show edit update]

  def new
    @rule = RewardRule.new
  end

  def edit
  end

  def index
    @rules = RewardRule.all
  end

  def create
    @rule = RewardRule.new(rule_params)
    if @rule.save
      redirect_to admin_reward_rules_path
    else
      render :new
    end
  end

  def update
    if @rule.update(rule_params)
      redirect_to admin_reward_rules_path
    else
      render :edit
    end
  end

  private

  def set_rule
    @rule = RewardRule.find(params[:id])
  end
  
  def rule_params
    params.require(:reward_rule).permit(:title, :left_value, :comparsion, :right_value, :additional)
  end
end

app/helpers/reward_rules_helper.rb
module RewardRulesHelper
end

app/views/admin/reward_rules/_form.html.erb
<%= form_with model: [:admin, object] do |form| %>
  <div class="container-fluid m-0 col-lg-6">
    <div class="form-floating my-3">
      <%= form.text_field :title, class: "form-control" %>
      <%= form.label t('.title'), for: :title %>
    </div>
    <div class="form-floating my-3">
      <%= form.text_area :left_value, class: "form-control vh-50", id: :leftValue, style: "height: 150px", required: true %>
      <%= form.label t('.left_value'), for: :leftValue %>
    </div>
    <div class="form-floating col-lg-3">
      <%= form.select :comparsion, %w(< > == !=), {}, class: "form-select", id: "comparsion" %>
      <%= form.label t('.comparsion'), for: "comparsion" %>
    </div>
    <div class="form-floating my-3">
      <%= form.text_area :right_value, class: "form-control vh-50", id: :rightValue, style: "height: 150px", required: true %>
      <%= form.label t('.right_value'), for: :rightValue %>
    </div>
    <div class="form-floating my-3">
      <%= form.text_field :additional, class: "form-control" %>
      <%= form.label t('.additional'), for: :additional %>
    </div>

    <div>
      <%= form.submit object.new_record? ? t('create') : t('update'), class: "btn btn-primary col-lg-4" %>
    </div>

    <%= link_to t('nav_back'), admin_reward_rules_path, class: "btn btn-link mt-2"  %>
  </div>
<% end %>

app/views/admin/reward_rules/edit.html.erb
<h1><%= t('.edit_rule') %></h1>

<%= render "form", object: @rule %>

app/views/admin/reward_rules/index.html.erb
<h1><%= t('.reward_rules') %></h1>

<div class="col-md-1 my-2">
  <%= link_to t('.add_new'), new_admin_reward_rule_path, class: "btn btn-link my-2 border" %>
</div>

<% @rules.each do |rule| %>
  <div class="row my-2">
    <div class="col-md-3 mx-1">
      <%= render inline: "#{rule.title}" %>
    </div>
    <div class="col-md-2 mx-1">
      <%= link_to image_tag('edit.svg', size: 12), edit_admin_reward_rule_path(rule) %> |
      <%= link_to image_tag('delete.svg', size: 12), admin_reward_rule_path(rule), method: :delete %>
    </div>
  </div>
<% end %>

<%= link_to t('nav_back'), root_path %>

app/views/admin/reward_rules/new.html.erb
<h1><%= t('.new_rule') %></h1>

<%= render "form", object: @rule %>